# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    rate_limiter:
        api_v1:
            policy: fixed_window
            limit: 60
            interval: '1 minute'
            cache_pool: cache.api_v1_limiter

    cache:
        pools:
            cache.api_v1_limiter: null

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        rate_limiter:
            api_v1:
                limit: 2
        session:
            storage_factory_id: session.storage.factory.mock_file
